version: "3"
services:
  blurry-eyes:
    build: ./blurry-eyes
    ports:
      - 127.0.0.1:8001:80
  traffic-light-w:
    build: ./traffic-light-w
    ports:
      - 127.0.0.1:8002:8080
    links:
      - traffic-light-1004
  traffic-light-1004:
    build: ./traffic-light-w-internal
    ports:
      - 127.0.0.1:8080:80
